<a href="https://colab.research.google.com/github/sanjyot756-web/08/blob/main/numpy01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Creating NumPy Arrays

In [1]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [3]:
import numpy as np
np.array(my_list)

array([1, 2, 3])

In [4]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [5]:
np.array (my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Built-in Methods

In [14]:
np.arange(0,11,2)


array([ 0,  2,  4,  6,  8, 10])

In [15]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

zeros and ones

In [17]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [18]:
np.zeros(3)

array([0., 0., 0.])

In [19]:
np.ones(5)

array([1., 1., 1., 1., 1.])

linspace

In [21]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [22]:
np.linspace(0,10,50 )

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

eye

In [23]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

Random


rand

In [24]:
np.random.rand(2)

array([0.60783425, 0.68388528])

In [25]:
np.random.rand(5,5)

array([[0.92029922, 0.58800285, 0.87911264, 0.76416952, 0.79349606],
       [0.52510312, 0.1701958 , 0.09365648, 0.97975472, 0.45542121],
       [0.37278323, 0.19713587, 0.20778894, 0.78871749, 0.7020165 ],
       [0.32491627, 0.16883689, 0.03997684, 0.79118759, 0.3570521 ],
       [0.78832318, 0.19326269, 0.32504811, 0.83940975, 0.34293769]])

randn

In [26]:
np.random.randn(2)

array([-1.83115023, -0.49010275])

In [27]:
np.random.randn(5,5)

array([[-1.23499776, -1.37559672,  1.48590798, -0.74921501,  1.90589183],
       [ 0.29885053,  0.24988631,  0.24664763, -0.0688352 , -0.5951392 ],
       [ 0.35917265,  1.48497512,  0.43256607, -0.58549859, -0.04744425],
       [-0.89148648,  1.22068308, -1.44181435, -0.98146403,  0.25442511],
       [-2.43543366, -1.67531462,  1.27479285, -0.98728629,  1.51674124]])

randint

In [28]:
np.random.randint(1,100)

88

In [29]:
np.random.randint(1,100,10)

array([10, 43, 28, 17, 48, 82, 30, 11, 14, 84])

Array Attributes and Methods

In [32]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [33]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [34]:
ranarr

array([36, 32, 48, 32, 31, 22,  9,  5, 48,  6])

Reshape

In [35]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

max,min,argmax,argmin

In [36]:
ranarr

array([36, 32, 48, 32, 31, 22,  9,  5, 48,  6])

In [38]:
ranarr.max()

np.int64(48)

In [39]:
ranarr.argmax()

np.int64(2)

In [40]:
ranarr.min()

np.int64(5)

In [41]:
ranarr.argmin()

np.int64(7)

Shape

In [42]:
#Vector
arr.shape

(25,)

In [43]:
#notice the two sets of brackets
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [44]:
arr.reshape(1,25).shape

(1, 25)

In [45]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [46]:
arr.reshape(25,1).shape

(25, 1)

dtype

In [47]:
arr.dtype

dtype('int64')